// Code generated by goyacc -o parser.go expr.y. DO NOT EDIT.

//line expr.y:3
package ast

import __yyfmt__ "fmt"

//line expr.y:3

import (
//"reflect"
)

const IDENT = 57346
const NUMBER = 57347
const STRING = 57348
const BOOL = 57349
const NIL = 57350
const EQ = 57351
const AND = 57352
const OR = 57353
const NOTEQ = 57354
const GT = 57355
const GTE = 57356
const LT = 57357
const LTE = 57358
const ORR = 57359
const ACC = 57360
const IF = 57361
const ELSE = 57362
const FOR = 57363
const IN = 57364
const ACC2 = 57365
const CONST = 57366
const LAMB = 57367
const ADDEQ = 57368
const SUBEQ = 57369
const MULEQ = 57370
const DIVEQ = 57371
const VARIADIC = 57372
const AS = 57373
const EXIT = 57374
const END = 57375
const DO = 57376
const ELSEIF = 57377
const THEN = 57378
const SWITCH = 57379
const CASE = 57380
const DEFAULT = 57381
const FUNCTION = 57382
const ANNO = 57383
const BREAK = 57384
const EQT = 57385
const NOTEQT = 57386
const ADDADD = 57387
const SUBSUB = 57388
const NONIL = 57389
const UMINUS = 57390

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"NUMBER",
	"STRING",
	"BOOL",
	"NIL",
	"EQ",
	"AND",
	"OR",
	"NOTEQ",
	"GT",
	"GTE",
	"LT",
	"LTE",
	"ORR",
	"ACC",
	"IF",
	"ELSE",
	"FOR",
	"IN",
	"ACC2",
	"CONST",
	"LAMB",
	"ADDEQ",
	"SUBEQ",
	"MULEQ",
	"DIVEQ",
	"VARIADIC",
	"AS",
	"EXIT",
	"END",
	"DO",
	"ELSEIF",
	"THEN",
	"SWITCH",
	"CASE",
	"DEFAULT",
	"FUNCTION",
	"ANNO",
	"BREAK",
	"';'",
	"'='",
	"'?'",
	"':'",
	"EQT",
	"NOTEQT",
	"ADDADD",
	"SUBSUB",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'&'",
	"'|'",
	"'!'",
	"'^'",
	"'@'",
	"NONIL",
	"'['",
	"']'",
	"UMINUS",
	"'{'",
	"'}'",
	"','",
	"'('",
	"')'",
	"'~'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line expr.y:206

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 119,
	26, 80,
	27, 80,
	28, 80,
	29, 80,
	44, 80,
	-2, 61,
	-1, 120,
	26, 81,
	27, 81,
	28, 81,
	29, 81,
	44, 81,
	-2, 92,
}

const yyPrivate = 57344

const yyLast = 1243

var yyAct = [...]uint8{
	174, 2, 173, 193, 122, 154, 93, 72, 73, 79,
	89, 82, 83, 164, 150, 85, 181, 88, 197, 90,
	181, 159, 180, 91, 94, 196, 95, 96, 97, 98,
	99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
	109, 110, 111, 112, 113, 114, 159, 147, 61, 153,
	116, 140, 141, 143, 118, 121, 123, 124, 125, 126,
	127, 128, 94, 130, 131, 132, 133, 134, 135, 136,
	137, 138, 139, 142, 3, 57, 58, 59, 60, 117,
	200, 87, 158, 76, 195, 152, 144, 92, 162, 54,
	145, 86, 146, 56, 175, 205, 5, 220, 191, 151,
	176, 48, 218, 68, 69, 70, 71, 217, 204, 214,
	194, 190, 211, 194, 48, 165, 84, 61, 161, 188,
	115, 67, 25, 26, 27, 28, 35, 30, 31, 119,
	29, 51, 50, 55, 32, 37, 38, 39, 40, 41,
	42, 43, 44, 54, 156, 169, 170, 53, 172, 129,
	52, 120, 94, 167, 88, 48, 45, 171, 178, 179,
	182, 183, 155, 186, 177, 81, 187, 185, 36, 168,
	49, 80, 33, 34, 46, 47, 25, 26, 27, 28,
	35, 30, 31, 198, 29, 51, 50, 55, 77, 201,
	202, 184, 75, 24, 203, 207, 206, 15, 208, 209,
	210, 78, 149, 80, 192, 54, 74, 4, 215, 1,
	0, 54, 0, 219, 0, 0, 166, 48, 0, 221,
	0, 0, 0, 48, 0, 0, 0, 0, 155, 32,
	37, 38, 39, 40, 41, 42, 43, 44, 54, 0,
	0, 0, 53, 30, 31, 52, 29, 51, 50, 55,
	48, 45, 29, 51, 50, 55, 199, 0, 0, 0,
	0, 0, 0, 36, 0, 49, 0, 33, 34, 46,
	47, 25, 26, 27, 28, 35, 30, 31, 0, 29,
	51, 50, 55, 63, 64, 65, 66, 0, 0, 157,
	32, 37, 38, 39, 40, 41, 42, 43, 44, 54,
	0, 62, 0, 53, 0, 0, 52, 0, 0, 0,
	0, 48, 45, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 36, 0, 49, 0, 33, 34,
	46, 47, 25, 26, 27, 28, 35, 30, 31, 0,
	29, 51, 50, 55, 163, 32, 37, 38, 39, 40,
	41, 42, 43, 44, 54, 0, 0, 0, 53, 0,
	0, 52, 0, 0, 0, 0, 48, 45, 0, 222,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 36,
	0, 49, 0, 33, 34, 46, 47, 25, 26, 27,
	28, 35, 30, 31, 0, 29, 51, 50, 55, 32,
	37, 38, 39, 40, 41, 42, 43, 44, 54, 0,
	0, 0, 53, 0, 0, 52, 0, 0, 0, 0,
	48, 45, 0, 0, 0, 0, 216, 0, 0, 0,
	0, 0, 0, 36, 0, 49, 0, 33, 34, 46,
	47, 25, 26, 27, 28, 35, 30, 31, 0, 29,
	51, 50, 55, 32, 37, 38, 39, 40, 41, 42,
	43, 44, 54, 0, 0, 0, 53, 0, 0, 52,
	0, 0, 0, 0, 48, 45, 0, 213, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 36, 0, 49,
	0, 33, 34, 46, 47, 25, 26, 27, 28, 35,
	30, 31, 0, 29, 51, 50, 55, 32, 37, 38,
	39, 40, 41, 42, 43, 44, 54, 0, 0, 0,
	53, 0, 0, 52, 0, 0, 0, 0, 48, 45,
	0, 0, 212, 0, 0, 0, 0, 0, 0, 0,
	0, 36, 0, 49, 0, 33, 34, 46, 47, 25,
	26, 27, 28, 35, 30, 31, 0, 29, 51, 50,
	55, 32, 37, 38, 39, 40, 41, 42, 43, 44,
	54, 0, 0, 0, 53, 0, 0, 52, 0, 0,
	0, 0, 48, 45, 0, 0, 189, 0, 0, 0,
	0, 0, 0, 0, 0, 36, 0, 49, 0, 33,
	34, 46, 47, 25, 26, 27, 28, 35, 30, 31,
	0, 29, 51, 50, 55, 32, 37, 38, 39, 40,
	41, 42, 43, 44, 54, 0, 0, 0, 53, 0,
	0, 52, 0, 0, 0, 0, 48, 45, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 36,
	0, 49, 160, 33, 34, 46, 47, 25, 26, 27,
	28, 35, 30, 31, 0, 29, 51, 50, 55, 32,
	37, 38, 39, 40, 41, 42, 43, 44, 54, 0,
	0, 0, 53, 0, 0, 52, 0, 0, 0, 0,
	48, 45, 0, 0, 0, 0, 0, 0, 151, 0,
	0, 0, 0, 36, 0, 49, 0, 33, 34, 46,
	47, 25, 26, 27, 28, 35, 30, 31, 0, 29,
	51, 50, 55, 32, 37, 38, 39, 40, 41, 42,
	43, 44, 54, 0, 0, 0, 53, 0, 0, 52,
	0, 0, 0, 0, 48, 45, 0, 0, 0, 0,
	148, 0, 0, 0, 0, 0, 0, 36, 0, 49,
	0, 33, 34, 46, 47, 25, 26, 27, 28, 35,
	30, 31, 0, 29, 51, 50, 55, 32, 37, 38,
	39, 40, 41, 42, 43, 44, 54, 0, 0, 0,
	53, 0, 0, 52, 0, 0, 0, 0, 48, 45,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 36, 0, 49, 0, 33, 34, 46, 47, 25,
	26, 27, 28, 35, 30, 31, 0, 29, 51, 50,
	55, 32, 37, 38, 39, 40, 41, 42, 43, 44,
	54, 0, 0, 0, 53, 0, 0, 52, 0, 0,
	0, 0, 48, 45, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 49, 0, 33,
	34, 46, 47, 25, 26, 27, 28, 35, 30, 31,
	0, 29, 51, 50, 55, 32, 37, 38, 39, 40,
	41, 42, 43, 44, 54, 0, 0, 0, 53, 0,
	0, 0, 0, 0, 0, 0, 48, 45, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 49, 0, 33, 34, 46, 47, 25, 26, 27,
	28, 35, 30, 31, 0, 29, 51, 50, 55, 32,
	37, 38, 39, 40, 41, 42, 43, 44, 54, 0,
	0, 0, 53, 0, 0, 0, 0, 0, 0, 0,
	48, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 49, 0, 33, 34, 46,
	47, 25, 26, 27, 28, 35, 30, 31, 0, 29,
	51, 50, 55, 32, 37, 38, 39, 40, 41, 42,
	43, 44, 54, 0, 0, 0, 53, 0, 0, 0,
	0, 0, 0, 0, 48, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 33, 34, 46, 47, 25, 26, 27, 28, 35,
	30, 31, 0, 29, 51, 50, 55, 32, 37, 38,
	39, 40, 41, 42, 43, 0, 54, 0, 0, 0,
	53, 0, 0, 0, 0, 0, 0, 0, 48, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 33, 34, 46, 47, 25,
	26, 27, 28, 35, 30, 31, 0, 29, 51, 50,
	55, 32, 37, 0, 39, 40, 41, 42, 43, 0,
	54, 0, 0, 0, 53, 0, 0, 0, 0, 0,
	0, 0, 48, 0, 0, 54, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 48, 0, 33,
	34, 46, 47, 25, 26, 27, 28, 35, 30, 31,
	0, 29, 51, 50, 55, 13, 17, 20, 19, 21,
	27, 28, 35, 30, 31, 0, 29, 51, 50, 55,
	10, 0, 9, 0, 0, 14, 0, 0, 0, 0,
	0, 0, 0, 18, 0, 0, 0, 0, 11, 54,
	0, 16, 0, 12, 0, 0, 0, 0, 54, 0,
	0, 48, 0, 7, 0, 0, 0, 0, 0, 6,
	48, 0, 0, 23, 0, 0, 8, 0, 0, 22,
	46, 47, 25, 26, 27, 28, 35, 30, 31, 0,
	29, 51, 50, 55, 0, 35, 30, 31, 0, 29,
	51, 50, 55,
}

var yyPact = [...]int16{
	1151, -1000, 768, 49, 257, 77, 1151, 1151, 197, 161,
	1151, 1151, -1000, 91, 1151, -1000, 13, -60, 1151, -1000,
	-1000, -1000, 1151, 1151, -1000, 1151, 1151, 1151, 1151, 1151,
	1151, 1151, 1151, 1151, 1151, 1151, 1151, 1151, 1151, 1151,
	1151, 1151, 1151, 1151, 1151, 150, -1000, -1000, -1000, 1151,
	-1000, -1000, 14, 1151, 1151, 1151, 1151, 1151, 1151, 1151,
	1151, 1151, 1151, 1151, 1151, 1151, 1151, 1151, 1151, 1151,
	1151, 1151, 193, -1000, -15, 7, -1000, -14, 40, -1000,
	44, 25, 714, 660, 1151, -1000, -19, 150, -1000, 139,
	768, 220, 19, -46, 768, 1107, 1107, 1180, 1180, 193,
	193, 193, 1171, 1171, 1171, 187, 822, 1092, 1038, 1171,
	1171, 1171, 1171, 1171, 984, -1000, 606, 1151, 1171, -20,
	-1000, 84, 42, 281, 930, 71, 71, 71, 71, -56,
	930, 71, 71, 71, 71, 930, 71, 71, 71, 71,
	90, 150, -1000, 165, 1151, 1151, 153, 1151, 1151, 61,
	-1000, 1151, 876, 150, -47, -1000, -1000, -1000, -1000, 1151,
	1151, 125, 1151, -1000, -1000, 1151, -1000, -1000, 40, 768,
	768, 97, 552, 78, 768, -1000, 38, -1000, -21, -51,
	1151, 150, 768, 984, -1000, 17, 768, 876, 1151, 1151,
	-1000, 1151, 75, -1000, 1151, 1151, 1151, 1151, 79, -1000,
	-1000, 498, 444, 76, -1000, 1151, -1000, 390, 74, -1000,
	69, -1000, 1151, -1000, -1000, 64, 1151, -1000, -1000, 336,
	-1000, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 209, 0, 74, 207, 96, 206, 2, 204, 202,
	197, 5, 3, 14, 6, 193, 87, 192, 4, 188,
	9,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 8, 8, 12,
	9, 9, 13, 7, 7, 6, 6, 11, 11, 11,
	4, 4, 15, 3, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 10, 10, 18, 18, 5, 17, 17,
	19, 19, 19, 20, 20, 16, 16, 14, 14, 14,
}

var yyR2 = [...]int8{
	0, 1, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 2, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
	2, 2, 2, 2, 5, 2, 2, 5, 5, 9,
	7, 5, 7, 6, 8, 4, 7, 1, 3, 2,
	3, 1, 1, 7, 6, 3, 2, 1, 2, 4,
	1, 2, 4, 0, 1, 1, 3, 0, 1, 3,
	3, 3, 3, 1, 1, 1, 1, 1, 4, 3,
	3, 3, 1, 1, 6, 0, 1, 4, 0, 1,
	1, 3, 2, 3, 3, 0, 1, 1, 3, 2,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, 58, 52, 65, 21,
	19, 37, 42, 4, 24, -10, 40, 5, 32, 7,
	6, 8, 68, 62, -15, 51, 52, 53, 54, 59,
	56, 57, 9, 47, 48, 55, 43, 10, 11, 12,
	13, 14, 15, 16, 17, 31, 49, 50, 30, 45,
	61, 60, 25, 22, 18, 62, 44, 26, 27, 28,
	29, 68, 44, 26, 27, 28, 29, 44, 26, 27,
	28, 29, -2, -2, -6, -17, -3, -19, 4, -20,
	6, 4, -2, -2, 25, -2, -3, 68, 4, 70,
	-2, -2, -16, -14, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -3, -2, 65, -2, -3,
	-5, -2, -18, -2, -2, -2, -2, -2, -2, -16,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	66, 67, 66, 67, 46, 46, 67, 22, 36, -9,
	-13, 38, -2, 68, -11, -3, 5, 69, 63, 67,
	46, -2, 46, 63, 69, 25, -3, -20, 4, -2,
	-2, 4, -2, -7, -2, 33, 39, -13, -14, -11,
	69, 67, -2, -2, 66, -18, -2, -2, 22, 34,
	33, 20, -8, -12, 35, 46, 46, 69, -7, -3,
	63, -2, -2, -7, 33, 20, -12, -2, -7, -7,
	-7, 33, 34, 33, 33, -7, 36, 33, 33, -2,
	33, -7, 33,
}

var yyDef = [...]int8{
	0, -2, 1, 61, 0, 92, 0, 0, 98, 0,
	0, 0, 57, 83, 0, 62, 0, 84, 0, 85,
	86, 87, 0, 105, 93, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 14, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 40, 41, 42, 0,
	45, 46, 0, 0, 0, 95, 0, 0, 0, 0,
	0, 105, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 39, 43, 0, 0, 75, 99, 83, 100,
	0, 0, 0, 0, 0, 59, 0, 77, 83, 0,
	66, 0, 0, 106, 107, 2, 3, 4, 5, 6,
	7, 8, 9, 10, 11, 12, 13, 30, 31, 32,
	33, 34, 35, 36, 37, 38, 0, 0, 60, -2,
	-2, 82, 0, 96, 15, 18, 21, 24, 27, 0,
	16, 19, 22, 25, 28, 17, 20, 23, 26, 29,
	0, 0, 90, 102, 0, 0, 0, 0, 73, 0,
	70, 0, 58, 77, 0, 78, 65, 89, 91, 109,
	0, 0, 95, 97, 88, 0, 76, 101, 0, 104,
	103, 0, 0, 0, 74, 55, 0, 71, 0, 0,
	73, 0, 108, 44, 48, 0, 96, 47, 0, 0,
	51, 73, 0, 67, 0, 73, 73, 73, 0, 79,
	94, 0, 0, 0, 53, 73, 68, 0, 0, 72,
	0, 64, 0, 50, 52, 0, 73, 56, 63, 0,
	54, 69, 49,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 58, 3, 3, 3, 55, 56, 3,
	68, 69, 53, 51, 67, 52, 3, 54, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 46, 43,
	3, 44, 3, 45, 60, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 62, 3, 63, 59, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 65, 57, 66, 70,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 47, 48, 49, 50, 61, 64,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:42
		{
			yylex.(Setter).SetRoot(yyS[yypt-0].node)
			yyVAL.node = yyS[yypt-0].node
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:46
		{
			yyVAL.node = &Binary{Op: "+", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:47
		{
			yyVAL.node = &Binary{Op: "-", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:48
		{
			yyVAL.node = &Binary{Op: "*", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:49
		{
			yyVAL.node = &Binary{Op: "/", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:50
		{
			yyVAL.node = &Binary{Op: "^", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:51
		{
			yyVAL.node = &Binary{Op: "&", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:52
		{
			yyVAL.node = &Binary{Op: "|", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:53
		{
			yyVAL.node = &Binary{Op: "==", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:54
		{
			yyVAL.node = &Binary{Op: "===", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:55
		{
			yyVAL.node = &Binary{Op: "!==", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:56
		{
			yyVAL.node = &Binary{Op: "%", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:57
		{
			yyVAL.node = &Binary{Op: ";", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:58
		{
			yyVAL.node = yyDollar[1].node
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:59
		{
			yyVAL.node = &Set{L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:60
		{
			yyVAL.node = &Set{L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:61
		{
			yyVAL.node = &Set{L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:62
		{
			yyVAL.node = &Binary{Op: "+=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:63
		{
			yyVAL.node = &Binary{Op: "+=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:64
		{
			yyVAL.node = &Binary{Op: "+=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:65
		{
			yyVAL.node = &Binary{Op: "-=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:66
		{
			yyVAL.node = &Binary{Op: "-=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:67
		{
			yyVAL.node = &Binary{Op: "-=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:68
		{
			yyVAL.node = &Binary{Op: "*=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:69
		{
			yyVAL.node = &Binary{Op: "*=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:70
		{
			yyVAL.node = &Binary{Op: "*=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:71
		{
			yyVAL.node = &Binary{Op: "/=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:72
		{
			yyVAL.node = &Binary{Op: "/=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:73
		{
			yyVAL.node = &Binary{Op: "/=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:74
		{
			yyVAL.node = &Binary{Op: "&&", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:75
		{
			yyVAL.node = &Binary{Op: "||", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:76
		{
			yyVAL.node = &Binary{Op: "!=", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:77
		{
			yyVAL.node = &Binary{Op: ">", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:78
		{
			yyVAL.node = &Binary{Op: ">=", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:79
		{
			yyVAL.node = &Binary{Op: "<", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:80
		{
			yyVAL.node = &Binary{Op: "<=", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:82
		{
			yyVAL.node = &Binary{Op: "orr", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:83
		{
			yyVAL.node = &Binary{Op: "as", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:84
		{
			yyVAL.node = &Unary{Op: "!", X: yyS[yypt-0].node}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:85
		{
			yyVAL.node = &Unary{Op: "++", X: yyDollar[1].node}
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:86
		{
			yyVAL.node = &Unary{Op: "--", X: yyDollar[1].node}
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:87
		{
			yyVAL.node = &Unary{Op: "...", X: yyDollar[1].node}
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:88
		{
			yyVAL.node = &Unary{Op: "-", X: yyS[yypt-0].node}
		}
	case 44:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expr.y:89
		{
			yyVAL.node = &Ternary{C: yyDollar[1].node, L: yyDollar[3].node, R: yyDollar[5].node}
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:90
		{
			yyVAL.node = &NotNil{yyDollar[1].node}
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:91
		{
			yyVAL.node = &NotNil{yyDollar[1].node}
		}
	case 47:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expr.y:92
		{
			yyVAL.node = &Lambda{L: yyDollar[2].strs, R: yyDollar[5].node}
		}
	case 48:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expr.y:93
		{
			yyVAL.node = &Lambda2{L: yyDollar[1].node, R: yyDollar[4].node}
		}
	case 49:
		yyDollar = yyS[yypt-9 : yypt+1]
//line expr.y:94
		{
			yyVAL.node = &ForRange{KName: yyDollar[2].str, VName: yyDollar[4].str, Var: yyDollar[6].node, Do: yyDollar[8].node}
		}
	case 50:
		yyDollar = yyS[yypt-7 : yypt+1]
//line expr.y:95
		{
			yyVAL.node = &ForRange{VName: yyDollar[2].str, Var: yyDollar[4].node, Do: yyDollar[6].node}
		}
	case 51:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expr.y:96
		{
			yyVAL.node = &IfElse{Cond: yyDollar[2].node, Then: yyDollar[4].node}
		}
	case 52:
		yyDollar = yyS[yypt-7 : yypt+1]
//line expr.y:97
		{
			yyVAL.node = &IfElse{Cond: yyDollar[2].node, Then: yyDollar[4].node, Else: yyDollar[6].node}
		}
	case 53:
		yyDollar = yyS[yypt-6 : yypt+1]
//line expr.y:98
		{
			yyVAL.node = &IfElse{Cond: yyDollar[2].node, Then: yyDollar[4].node, Elseifs: yyDollar[5].nodes}
		}
	case 54:
		yyDollar = yyS[yypt-8 : yypt+1]
//line expr.y:99
		{
			yyVAL.node = &IfElse{Cond: yyDollar[2].node, Then: yyDollar[4].node, Elseifs: yyDollar[5].nodes, Else: yyDollar[7].node}
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:100
		{
			yyVAL.node = &Switch{Var: yyDollar[2].node, Cases: yyDollar[3].nodes}
		}
	case 56:
		yyDollar = yyS[yypt-7 : yypt+1]
//line expr.y:101
		{
			yyVAL.node = &Switch{Var: yyDollar[2].node, Cases: yyDollar[3].nodes, Default: yyDollar[6].node}
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:102
		{
			yyVAL.node = &Break{}
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:106
		{
			yyVAL.node = &Lambda{L: []string{yyDollar[1].str}, R: yyDollar[3].node}
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:109
		{
			yyVAL.node = &Const{L: yyDollar[2].node}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:110
		{
			yyVAL.node = &Binary{Op: "in", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:111
		{
			yyVAL.node = yyDollar[1].node
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:112
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 63:
		yyDollar = yyS[yypt-7 : yypt+1]
//line expr.y:113
		{
			yyVAL.node = &Set{L: yyDollar[2].node, R: &Lambda{L: yyDollar[4].strs, R: yyDollar[6].node}}
		}
	case 64:
		yyDollar = yyS[yypt-6 : yypt+1]
//line expr.y:114
		{
			yyVAL.node = &Lambda{L: yyDollar[3].strs, R: yyDollar[5].node}
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:115
		{
			yyVAL.node = &RangeValue{L: yyDollar[1].num, R: yyDollar[3].num}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:120
		{
			yyVAL.nodes = []Node{yyDollar[1].node}
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:121
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 69:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:124
		{
			yyVAL.node = &ElseIf{Cond: yyDollar[2].node, Then: yyDollar[4].node}
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:127
		{
			yyVAL.nodes = []Node{yyDollar[1].node}
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:128
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 72:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:131
		{
			yyVAL.node = &Case{Vars: yyDollar[2].nodes, Do: yyDollar[4].node}
		}
	case 73:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expr.y:134
		{
			yyVAL.node = nil
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:135
		{
			yyVAL.node = yyDollar[1].node
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:139
		{
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:140
		{
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[3].str)
		}
	case 77:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expr.y:143
		{
			yyVAL.strs = []string{}
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:144
		{
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:145
		{
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[3].str)
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:147
		{
			yyVAL.node = &Access{L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:148
		{
			yyVAL.node = &Access{L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:151
		{
			yyVAL.node = &Access{L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:154
		{
			yyVAL.node = &Variable{Name: yyDollar[1].str}
			yyVAL.str = yyDollar[1].str
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:157
		{
			yyVAL.node = &Number{Val: yyS[yypt-0].num}
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:158
		{
			yyVAL.node = &Bool{Val: yyS[yypt-0].boolean}
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:159
		{
			yyVAL.node = &String{Val: yyS[yypt-0].str}
			yyVAL.str = yyDollar[1].str
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:160
		{
			yyVAL.node = &Nil{}
		}
	case 88:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:161
		{
			yyVAL.node = &Call{Name: yyS[yypt-3].str, Args: yyS[yypt-1].nodes}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:162
		{
			yyVAL.node = yyS[yypt-1].node
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:163
		{
			yyVAL.node = &MapSet{Kvs: yyDollar[2].kvs}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:164
		{
			yyVAL.node = &ArrDef{V: yyDollar[2].nodes}
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:165
		{
			yyVAL.node = yyDollar[1].node
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:166
		{
			yyVAL.node = yyDollar[1].node
		}
	case 94:
		yyDollar = yyS[yypt-6 : yypt+1]
//line expr.y:167
		{
			yyVAL.node = &SliceCut{V: yyDollar[1].node, St: yyDollar[3].node, Ed: yyDollar[5].node}
		}
	case 95:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expr.y:175
		{
			yyVAL.node = nil
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:176
		{
			yyVAL.node = yyDollar[1].node
		}
	case 97:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:179
		{
			yyVAL.node = &ArrAccess{L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 98:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expr.y:182
		{
			yyVAL.kvs = nil
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:183
		{
			yyVAL.kvs = yyDollar[1].kvs
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:186
		{
			yyVAL.kvs = []KV{yyDollar[1].kv}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:187
		{
			yyVAL.kvs = append(yyDollar[1].kvs, yyDollar[3].kv)
		}
	case 102:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:188
		{
			yyVAL.kvs = yyDollar[1].kvs
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:191
		{
			yyVAL.kv = KV{K: yyDollar[1].str, V: yyDollar[3].node}
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:192
		{
			yyVAL.kv = KV{K: yyDollar[1].str, V: yyDollar[3].node}
		}
	case 105:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expr.y:196
		{
			yyVAL.nodes = nil
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:197
		{
			yyVAL.nodes = yyS[yypt-0].nodes
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:201
		{
			yyVAL.nodes = []Node{yyS[yypt-0].node}
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:202
		{
			yyVAL.nodes = append(yyS[yypt-2].nodes, yyS[yypt-0].node)
		}
	case 109:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:203
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	}
	goto yystack /* stack new state and value */
}
