// Code generated by goyacc -o parser.go expr.y. DO NOT EDIT.

//line expr.y:3
package ast

import __yyfmt__ "fmt"

//line expr.y:3

import (
//"reflect"
)

const IDENT = 57346
const NUMBER = 57347
const STRING = 57348
const BOOL = 57349
const NIL = 57350
const EQ = 57351
const AND = 57352
const OR = 57353
const NOTEQ = 57354
const GT = 57355
const GTE = 57356
const LT = 57357
const LTE = 57358
const ORR = 57359
const ACC = 57360
const IF = 57361
const ELSE = 57362
const FOR = 57363
const IN = 57364
const ACC2 = 57365
const CONST = 57366
const LAMB = 57367
const ADDEQ = 57368
const SUBEQ = 57369
const MULEQ = 57370
const DIVEQ = 57371
const VARIADIC = 57372
const AS = 57373
const EXIT = 57374
const END = 57375
const DO = 57376
const ELSEIF = 57377
const THEN = 57378
const SWITCH = 57379
const CASE = 57380
const DEFAULT = 57381
const FUNCTION = 57382
const ANNO = 57383
const BREAK = 57384
const EQT = 57385
const NOTEQT = 57386
const ADDADD = 57387
const SUBSUB = 57388
const NONIL = 57389
const UMINUS = 57390

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"NUMBER",
	"STRING",
	"BOOL",
	"NIL",
	"EQ",
	"AND",
	"OR",
	"NOTEQ",
	"GT",
	"GTE",
	"LT",
	"LTE",
	"ORR",
	"ACC",
	"IF",
	"ELSE",
	"FOR",
	"IN",
	"ACC2",
	"CONST",
	"LAMB",
	"ADDEQ",
	"SUBEQ",
	"MULEQ",
	"DIVEQ",
	"VARIADIC",
	"AS",
	"EXIT",
	"END",
	"DO",
	"ELSEIF",
	"THEN",
	"SWITCH",
	"CASE",
	"DEFAULT",
	"FUNCTION",
	"ANNO",
	"BREAK",
	"';'",
	"'='",
	"'?'",
	"':'",
	"EQT",
	"NOTEQT",
	"ADDADD",
	"SUBSUB",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'&'",
	"'|'",
	"'!'",
	"'^'",
	"'@'",
	"NONIL",
	"'['",
	"']'",
	"UMINUS",
	"'{'",
	"'}'",
	"','",
	"'('",
	"')'",
	"'~'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line expr.y:206

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 117,
	26, 79,
	27, 79,
	28, 79,
	29, 79,
	44, 79,
	-2, 61,
	-1, 118,
	26, 80,
	27, 80,
	28, 80,
	29, 80,
	44, 80,
	-2, 91,
}

const yyPrivate = 57344

const yyLast = 1240

var yyAct = [...]uint8{
	172, 2, 171, 191, 120, 152, 91, 71, 72, 78,
	88, 81, 82, 162, 148, 84, 179, 179, 195, 178,
	60, 87, 89, 92, 194, 93, 94, 95, 96, 97,
	98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
	108, 109, 110, 111, 112, 157, 145, 151, 157, 114,
	138, 139, 141, 116, 119, 121, 122, 123, 124, 125,
	126, 92, 128, 129, 130, 131, 132, 133, 134, 135,
	136, 137, 140, 3, 115, 56, 57, 58, 59, 198,
	193, 156, 75, 142, 150, 86, 90, 53, 5, 160,
	85, 144, 143, 55, 67, 68, 69, 70, 203, 47,
	173, 62, 63, 64, 65, 149, 174, 218, 163, 216,
	215, 202, 66, 192, 212, 209, 159, 60, 113, 61,
	24, 25, 26, 27, 34, 29, 30, 117, 28, 50,
	49, 54, 31, 36, 37, 38, 39, 40, 41, 42,
	43, 53, 118, 167, 168, 52, 170, 127, 51, 47,
	92, 165, 83, 47, 44, 186, 176, 177, 180, 181,
	153, 184, 175, 154, 185, 183, 35, 166, 48, 79,
	32, 33, 45, 46, 24, 25, 26, 27, 34, 29,
	30, 196, 28, 50, 49, 54, 189, 199, 200, 182,
	87, 169, 201, 205, 204, 80, 206, 207, 208, 188,
	76, 192, 53, 77, 74, 79, 213, 23, 53, 15,
	147, 217, 190, 164, 47, 73, 4, 219, 1, 0,
	47, 0, 0, 0, 0, 153, 31, 36, 37, 38,
	39, 40, 41, 42, 43, 53, 0, 0, 0, 52,
	29, 30, 51, 28, 50, 49, 54, 47, 44, 28,
	50, 49, 54, 197, 0, 0, 0, 0, 0, 0,
	35, 0, 48, 0, 32, 33, 45, 46, 24, 25,
	26, 27, 34, 29, 30, 0, 28, 50, 49, 54,
	0, 0, 0, 0, 0, 0, 155, 31, 36, 37,
	38, 39, 40, 41, 42, 43, 53, 0, 0, 0,
	52, 0, 0, 51, 0, 0, 0, 0, 47, 44,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 35, 0, 48, 0, 32, 33, 45, 46, 24,
	25, 26, 27, 34, 29, 30, 0, 28, 50, 49,
	54, 161, 31, 36, 37, 38, 39, 40, 41, 42,
	43, 53, 0, 0, 0, 52, 0, 0, 51, 0,
	0, 0, 0, 47, 44, 0, 220, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 35, 0, 48, 0,
	32, 33, 45, 46, 24, 25, 26, 27, 34, 29,
	30, 0, 28, 50, 49, 54, 31, 36, 37, 38,
	39, 40, 41, 42, 43, 53, 0, 0, 0, 52,
	0, 0, 51, 0, 0, 0, 0, 47, 44, 0,
	0, 0, 0, 214, 0, 0, 0, 0, 0, 0,
	35, 0, 48, 0, 32, 33, 45, 46, 24, 25,
	26, 27, 34, 29, 30, 0, 28, 50, 49, 54,
	31, 36, 37, 38, 39, 40, 41, 42, 43, 53,
	0, 0, 0, 52, 0, 0, 51, 0, 0, 0,
	0, 47, 44, 0, 211, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 35, 0, 48, 0, 32, 33,
	45, 46, 24, 25, 26, 27, 34, 29, 30, 0,
	28, 50, 49, 54, 31, 36, 37, 38, 39, 40,
	41, 42, 43, 53, 0, 0, 0, 52, 0, 0,
	51, 0, 0, 0, 0, 47, 44, 0, 0, 210,
	0, 0, 0, 0, 0, 0, 0, 0, 35, 0,
	48, 0, 32, 33, 45, 46, 24, 25, 26, 27,
	34, 29, 30, 0, 28, 50, 49, 54, 31, 36,
	37, 38, 39, 40, 41, 42, 43, 53, 0, 0,
	0, 52, 0, 0, 51, 0, 0, 0, 0, 47,
	44, 0, 0, 187, 0, 0, 0, 0, 0, 0,
	0, 0, 35, 0, 48, 0, 32, 33, 45, 46,
	24, 25, 26, 27, 34, 29, 30, 0, 28, 50,
	49, 54, 31, 36, 37, 38, 39, 40, 41, 42,
	43, 53, 0, 0, 0, 52, 0, 0, 51, 0,
	0, 0, 0, 47, 44, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 35, 0, 48, 158,
	32, 33, 45, 46, 24, 25, 26, 27, 34, 29,
	30, 0, 28, 50, 49, 54, 31, 36, 37, 38,
	39, 40, 41, 42, 43, 53, 0, 0, 0, 52,
	0, 0, 51, 0, 0, 0, 0, 47, 44, 0,
	0, 0, 0, 0, 0, 149, 0, 0, 0, 0,
	35, 0, 48, 0, 32, 33, 45, 46, 24, 25,
	26, 27, 34, 29, 30, 0, 28, 50, 49, 54,
	31, 36, 37, 38, 39, 40, 41, 42, 43, 53,
	0, 0, 0, 52, 0, 0, 51, 0, 0, 0,
	0, 47, 44, 0, 0, 0, 0, 146, 0, 0,
	0, 0, 0, 0, 35, 0, 48, 0, 32, 33,
	45, 46, 24, 25, 26, 27, 34, 29, 30, 0,
	28, 50, 49, 54, 31, 36, 37, 38, 39, 40,
	41, 42, 43, 53, 0, 0, 0, 52, 0, 0,
	51, 0, 0, 0, 0, 47, 44, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 35, 0,
	48, 0, 32, 33, 45, 46, 24, 25, 26, 27,
	34, 29, 30, 0, 28, 50, 49, 54, 31, 36,
	37, 38, 39, 40, 41, 42, 43, 53, 0, 0,
	0, 52, 0, 0, 51, 0, 0, 0, 0, 47,
	44, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 48, 0, 32, 33, 45, 46,
	24, 25, 26, 27, 34, 29, 30, 0, 28, 50,
	49, 54, 31, 36, 37, 38, 39, 40, 41, 42,
	43, 53, 0, 0, 0, 52, 0, 0, 0, 0,
	0, 0, 0, 47, 44, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 48, 0,
	32, 33, 45, 46, 24, 25, 26, 27, 34, 29,
	30, 0, 28, 50, 49, 54, 31, 36, 37, 38,
	39, 40, 41, 42, 43, 53, 0, 0, 0, 52,
	0, 0, 0, 0, 0, 0, 0, 47, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 48, 0, 32, 33, 45, 46, 24, 25,
	26, 27, 34, 29, 30, 0, 28, 50, 49, 54,
	31, 36, 37, 38, 39, 40, 41, 42, 43, 53,
	0, 0, 0, 52, 0, 0, 0, 0, 0, 0,
	0, 47, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 32, 33,
	45, 46, 24, 25, 26, 27, 34, 29, 30, 0,
	28, 50, 49, 54, 31, 36, 37, 38, 39, 40,
	41, 42, 0, 53, 0, 0, 0, 52, 0, 0,
	0, 0, 0, 0, 0, 47, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 32, 33, 45, 46, 24, 25, 26, 27,
	34, 29, 30, 0, 28, 50, 49, 54, 31, 36,
	0, 38, 39, 40, 41, 42, 0, 53, 0, 0,
	0, 52, 0, 0, 0, 0, 0, 0, 0, 47,
	0, 0, 53, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 47, 0, 32, 33, 45, 46,
	24, 25, 26, 27, 34, 29, 30, 0, 28, 50,
	49, 54, 13, 17, 19, 18, 20, 26, 27, 34,
	29, 30, 0, 28, 50, 49, 54, 10, 0, 9,
	0, 0, 14, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 11, 53, 0, 16, 0,
	12, 0, 0, 0, 0, 53, 0, 0, 47, 0,
	7, 0, 0, 0, 0, 0, 6, 47, 0, 0,
	22, 0, 0, 8, 0, 0, 21, 45, 46, 24,
	25, 26, 27, 34, 29, 30, 0, 28, 50, 49,
	54, 0, 34, 29, 30, 0, 28, 50, 49, 54,
}

var yyPact = [...]int16{
	1148, -1000, 765, 49, 75, 68, 1148, 1148, 199, 191,
	1148, 1148, -1000, 127, 1148, -1000, 17, -60, -1000, -1000,
	-1000, 1148, 1148, -1000, 1148, 1148, 1148, 1148, 1148, 1148,
	1148, 1148, 1148, 1148, 1148, 1148, 1148, 1148, 1148, 1148,
	1148, 1148, 1148, 1148, 186, -1000, -1000, -1000, 1148, -1000,
	-1000, 9, 1148, 1148, 1148, 1148, 1148, 1148, 1148, 1148,
	1148, 1148, 1148, 1148, 1148, 1148, 1148, 1148, 1148, 1148,
	1148, 190, -1000, -16, 6, -1000, -15, 37, -1000, 46,
	24, 711, 657, 1148, -1000, -21, 186, -1000, 158, 217,
	18, -19, 765, 1104, 1104, 1177, 1177, 190, 190, 190,
	1168, 1168, 1168, 184, 819, 1089, 1035, 1168, 1168, 1168,
	1168, 1168, 981, -1000, 603, 1148, 1168, -48, -1000, 119,
	43, 278, 927, 69, 69, 69, 69, -56, 927, 69,
	69, 69, 69, 927, 69, 69, 69, 69, 83, 186,
	-1000, 163, 1148, 1148, 187, 1148, 1148, 67, -1000, 1148,
	873, 186, -50, -1000, -1000, -1000, -1000, 1148, 1148, 123,
	1148, -1000, -1000, 1148, -1000, -1000, 37, 765, 765, 133,
	549, 166, 765, -1000, 34, -1000, -22, -51, 1148, 186,
	765, 981, -1000, 16, 765, 873, 1148, 1148, -1000, 1148,
	78, -1000, 1148, 1148, 1148, 1148, 82, -1000, -1000, 495,
	441, 81, -1000, 1148, -1000, 387, 77, -1000, 76, -1000,
	1148, -1000, -1000, 74, 1148, -1000, -1000, 333, -1000, -1000,
	-1000,
}

var yyPgo = [...]uint8{
	0, 218, 0, 73, 216, 88, 215, 2, 212, 210,
	209, 5, 3, 14, 6, 207, 86, 204, 4, 200,
	9,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 8, 8, 12, 9,
	9, 13, 7, 7, 6, 6, 11, 11, 11, 4,
	4, 15, 3, 10, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 10, 18, 18, 5, 17, 17, 19,
	19, 19, 20, 20, 16, 16, 14, 14, 14,
}

var yyR2 = [...]int8{
	0, 1, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 2, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
	2, 2, 2, 2, 5, 2, 2, 5, 5, 9,
	7, 5, 7, 6, 8, 4, 7, 1, 3, 2,
	3, 1, 1, 7, 6, 3, 1, 2, 4, 1,
	2, 4, 0, 1, 1, 3, 0, 1, 3, 3,
	3, 3, 1, 1, 1, 1, 1, 4, 3, 3,
	3, 1, 1, 6, 0, 1, 4, 0, 1, 1,
	3, 2, 3, 3, 0, 1, 1, 3, 2,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, 58, 52, 65, 21,
	19, 37, 42, 4, 24, -10, 40, 5, 7, 6,
	8, 68, 62, -15, 51, 52, 53, 54, 59, 56,
	57, 9, 47, 48, 55, 43, 10, 11, 12, 13,
	14, 15, 16, 17, 31, 49, 50, 30, 45, 61,
	60, 25, 22, 18, 62, 44, 26, 27, 28, 29,
	68, 44, 26, 27, 28, 29, 44, 26, 27, 28,
	29, -2, -2, -6, -17, -3, -19, 4, -20, 6,
	4, -2, -2, 25, -2, -3, 68, 4, 70, -2,
	-16, -14, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -3, -2, 65, -2, -3, -5, -2,
	-18, -2, -2, -2, -2, -2, -2, -16, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, 66, 67,
	66, 67, 46, 46, 67, 22, 36, -9, -13, 38,
	-2, 68, -11, -3, 5, 69, 63, 67, 46, -2,
	46, 63, 69, 25, -3, -20, 4, -2, -2, 4,
	-2, -7, -2, 33, 39, -13, -14, -11, 69, 67,
	-2, -2, 66, -18, -2, -2, 22, 34, 33, 20,
	-8, -12, 35, 46, 46, 69, -7, -3, 63, -2,
	-2, -7, 33, 20, -12, -2, -7, -7, -7, 33,
	34, 33, 33, -7, 36, 33, 33, -2, 33, -7,
	33,
}

var yyDef = [...]int8{
	0, -2, 1, 61, 0, 91, 0, 0, 97, 0,
	0, 0, 57, 82, 0, 62, 0, 83, 84, 85,
	86, 0, 104, 92, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 14, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 40, 41, 42, 0, 45,
	46, 0, 0, 0, 94, 0, 0, 0, 0, 0,
	104, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 39, 43, 0, 0, 74, 98, 82, 99, 0,
	0, 0, 0, 0, 59, 0, 76, 82, 0, 0,
	0, 105, 106, 2, 3, 4, 5, 6, 7, 8,
	9, 10, 11, 12, 13, 30, 31, 32, 33, 34,
	35, 36, 37, 38, 0, 0, 60, -2, -2, 81,
	0, 95, 15, 18, 21, 24, 27, 0, 16, 19,
	22, 25, 28, 17, 20, 23, 26, 29, 0, 0,
	89, 101, 0, 0, 0, 0, 72, 0, 69, 0,
	58, 76, 0, 77, 65, 88, 90, 108, 0, 0,
	94, 96, 87, 0, 75, 100, 0, 103, 102, 0,
	0, 0, 73, 55, 0, 70, 0, 0, 72, 0,
	107, 44, 48, 0, 95, 47, 0, 0, 51, 72,
	0, 66, 0, 72, 72, 72, 0, 78, 93, 0,
	0, 0, 53, 72, 67, 0, 0, 71, 0, 64,
	0, 50, 52, 0, 72, 56, 63, 0, 54, 68,
	49,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 58, 3, 3, 3, 55, 56, 3,
	68, 69, 53, 51, 67, 52, 3, 54, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 46, 43,
	3, 44, 3, 45, 60, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 62, 3, 63, 59, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 65, 57, 66, 70,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 47, 48, 49, 50, 61, 64,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:42
		{
			yylex.(Setter).SetRoot(yyS[yypt-0].node)
			yyVAL.node = yyS[yypt-0].node
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:46
		{
			yyVAL.node = &Binary{Op: "+", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:47
		{
			yyVAL.node = &Binary{Op: "-", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:48
		{
			yyVAL.node = &Binary{Op: "*", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:49
		{
			yyVAL.node = &Binary{Op: "/", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:50
		{
			yyVAL.node = &Binary{Op: "^", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:51
		{
			yyVAL.node = &Binary{Op: "&", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:52
		{
			yyVAL.node = &Binary{Op: "|", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:53
		{
			yyVAL.node = &Binary{Op: "==", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:54
		{
			yyVAL.node = &Binary{Op: "===", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:55
		{
			yyVAL.node = &Binary{Op: "!==", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:56
		{
			yyVAL.node = &Binary{Op: "%", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:57
		{
			yyVAL.node = &Binary{Op: ";", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:58
		{
			yyVAL.node = yyDollar[1].node
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:59
		{
			yyVAL.node = &Set{L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:60
		{
			yyVAL.node = &Set{L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:61
		{
			yyVAL.node = &Set{L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:62
		{
			yyVAL.node = &Binary{Op: "+=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:63
		{
			yyVAL.node = &Binary{Op: "+=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:64
		{
			yyVAL.node = &Binary{Op: "+=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:65
		{
			yyVAL.node = &Binary{Op: "-=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:66
		{
			yyVAL.node = &Binary{Op: "-=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:67
		{
			yyVAL.node = &Binary{Op: "-=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:68
		{
			yyVAL.node = &Binary{Op: "*=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:69
		{
			yyVAL.node = &Binary{Op: "*=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:70
		{
			yyVAL.node = &Binary{Op: "*=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:71
		{
			yyVAL.node = &Binary{Op: "/=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:72
		{
			yyVAL.node = &Binary{Op: "/=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:73
		{
			yyVAL.node = &Binary{Op: "/=", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:74
		{
			yyVAL.node = &Binary{Op: "&&", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:75
		{
			yyVAL.node = &Binary{Op: "||", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:76
		{
			yyVAL.node = &Binary{Op: "!=", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:77
		{
			yyVAL.node = &Binary{Op: ">", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:78
		{
			yyVAL.node = &Binary{Op: ">=", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:79
		{
			yyVAL.node = &Binary{Op: "<", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:80
		{
			yyVAL.node = &Binary{Op: "<=", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:82
		{
			yyVAL.node = &Binary{Op: "orr", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:83
		{
			yyVAL.node = &Binary{Op: "as", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:84
		{
			yyVAL.node = &Unary{Op: "!", X: yyS[yypt-0].node}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:85
		{
			yyVAL.node = &Unary{Op: "++", X: yyDollar[1].node}
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:86
		{
			yyVAL.node = &Unary{Op: "--", X: yyDollar[1].node}
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:87
		{
			yyVAL.node = &Unary{Op: "...", X: yyDollar[1].node}
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:88
		{
			yyVAL.node = &Unary{Op: "-", X: yyS[yypt-0].node}
		}
	case 44:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expr.y:89
		{
			yyVAL.node = &Ternary{C: yyDollar[1].node, L: yyDollar[3].node, R: yyDollar[5].node}
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:90
		{
			yyVAL.node = &NotNil{yyDollar[1].node}
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:91
		{
			yyVAL.node = &NotNil{yyDollar[1].node}
		}
	case 47:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expr.y:92
		{
			yyVAL.node = &Lambda{L: yyDollar[2].strs, R: yyDollar[5].node}
		}
	case 48:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expr.y:93
		{
			yyVAL.node = &Lambda2{L: yyDollar[1].node, R: yyDollar[4].node}
		}
	case 49:
		yyDollar = yyS[yypt-9 : yypt+1]
//line expr.y:94
		{
			yyVAL.node = &ForRange{KName: yyDollar[2].str, VName: yyDollar[4].str, Var: yyDollar[6].node, Do: yyDollar[8].node}
		}
	case 50:
		yyDollar = yyS[yypt-7 : yypt+1]
//line expr.y:95
		{
			yyVAL.node = &ForRange{VName: yyDollar[2].str, Var: yyDollar[4].node, Do: yyDollar[6].node}
		}
	case 51:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expr.y:96
		{
			yyVAL.node = &IfElse{Cond: yyDollar[2].node, Then: yyDollar[4].node}
		}
	case 52:
		yyDollar = yyS[yypt-7 : yypt+1]
//line expr.y:97
		{
			yyVAL.node = &IfElse{Cond: yyDollar[2].node, Then: yyDollar[4].node, Else: yyDollar[6].node}
		}
	case 53:
		yyDollar = yyS[yypt-6 : yypt+1]
//line expr.y:98
		{
			yyVAL.node = &IfElse{Cond: yyDollar[2].node, Then: yyDollar[4].node, Elseifs: yyDollar[5].nodes}
		}
	case 54:
		yyDollar = yyS[yypt-8 : yypt+1]
//line expr.y:99
		{
			yyVAL.node = &IfElse{Cond: yyDollar[2].node, Then: yyDollar[4].node, Elseifs: yyDollar[5].nodes, Else: yyDollar[7].node}
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:100
		{
			yyVAL.node = &Switch{Var: yyDollar[2].node, Cases: yyDollar[3].nodes}
		}
	case 56:
		yyDollar = yyS[yypt-7 : yypt+1]
//line expr.y:101
		{
			yyVAL.node = &Switch{Var: yyDollar[2].node, Cases: yyDollar[3].nodes, Default: yyDollar[6].node}
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:102
		{
			yyVAL.node = &Break{}
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:106
		{
			yyVAL.node = &Lambda{L: []string{yyDollar[1].str}, R: yyDollar[3].node}
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:109
		{
			yyVAL.node = &Const{L: yyDollar[2].node}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:110
		{
			yyVAL.node = &Binary{Op: "in", L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:111
		{
			yyVAL.node = yyDollar[1].node
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:112
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 63:
		yyDollar = yyS[yypt-7 : yypt+1]
//line expr.y:113
		{
			yyVAL.node = &Set{L: yyDollar[2].node, R: &Lambda{L: yyDollar[4].strs, R: yyDollar[6].node}}
		}
	case 64:
		yyDollar = yyS[yypt-6 : yypt+1]
//line expr.y:114
		{
			yyVAL.node = &Lambda{L: yyDollar[3].strs, R: yyDollar[5].node}
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:115
		{
			yyVAL.node = &RangeValue{L: yyDollar[1].num, R: yyDollar[3].num}
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:120
		{
			yyVAL.nodes = []Node{yyDollar[1].node}
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:121
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 68:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:124
		{
			yyVAL.node = &ElseIf{Cond: yyDollar[2].node, Then: yyDollar[4].node}
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:127
		{
			yyVAL.nodes = []Node{yyDollar[1].node}
		}
	case 70:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:128
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
		}
	case 71:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:131
		{
			yyVAL.node = &Case{Vars: yyDollar[2].nodes, Do: yyDollar[4].node}
		}
	case 72:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expr.y:134
		{
			yyVAL.node = nil
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:135
		{
			yyVAL.node = yyDollar[1].node
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:139
		{
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:140
		{
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[3].str)
		}
	case 76:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expr.y:143
		{
			yyVAL.strs = []string{}
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:144
		{
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:145
		{
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[3].str)
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:147
		{
			yyVAL.node = &Access{L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:148
		{
			yyVAL.node = &Access{L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:151
		{
			yyVAL.node = &Access{L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:154
		{
			yyVAL.node = &Variable{Name: yyDollar[1].str}
			yyVAL.str = yyDollar[1].str
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:157
		{
			yyVAL.node = &Number{Val: yyS[yypt-0].num}
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:158
		{
			yyVAL.node = &Bool{Val: yyS[yypt-0].boolean}
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:159
		{
			yyVAL.node = &String{Val: yyS[yypt-0].str}
			yyVAL.str = yyDollar[1].str
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:160
		{
			yyVAL.node = &Nil{}
		}
	case 87:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:161
		{
			yyVAL.node = &Call{Name: yyS[yypt-3].str, Args: yyS[yypt-1].nodes}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:162
		{
			yyVAL.node = yyS[yypt-1].node
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:163
		{
			yyVAL.node = &MapSet{Kvs: yyDollar[2].kvs}
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:164
		{
			yyVAL.node = &ArrDef{V: yyDollar[2].nodes}
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:165
		{
			yyVAL.node = yyDollar[1].node
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:166
		{
			yyVAL.node = yyDollar[1].node
		}
	case 93:
		yyDollar = yyS[yypt-6 : yypt+1]
//line expr.y:167
		{
			yyVAL.node = &SliceCut{V: yyDollar[1].node, St: yyDollar[3].node, Ed: yyDollar[5].node}
		}
	case 94:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expr.y:175
		{
			yyVAL.node = nil
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:176
		{
			yyVAL.node = yyDollar[1].node
		}
	case 96:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:179
		{
			yyVAL.node = &ArrAccess{L: yyDollar[1].node, R: yyDollar[3].node}
		}
	case 97:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expr.y:182
		{
			yyVAL.kvs = nil
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:183
		{
			yyVAL.kvs = yyDollar[1].kvs
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:186
		{
			yyVAL.kvs = []KV{yyDollar[1].kv}
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:187
		{
			yyVAL.kvs = append(yyDollar[1].kvs, yyDollar[3].kv)
		}
	case 101:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:188
		{
			yyVAL.kvs = yyDollar[1].kvs
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:191
		{
			yyVAL.kv = KV{K: yyDollar[1].str, V: yyDollar[3].node}
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:192
		{
			yyVAL.kv = KV{K: yyDollar[1].str, V: yyDollar[3].node}
		}
	case 104:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expr.y:196
		{
			yyVAL.nodes = nil
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:197
		{
			yyVAL.nodes = yyS[yypt-0].nodes
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:201
		{
			yyVAL.nodes = []Node{yyS[yypt-0].node}
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:202
		{
			yyVAL.nodes = append(yyS[yypt-2].nodes, yyS[yypt-0].node)
		}
	case 108:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:203
		{
			yyVAL.nodes = yyDollar[1].nodes
		}
	}
	goto yystack /* stack new state and value */
}
